"""Add versions

Revision ID: 5a61177eee13
Revises: 364c0924848c
Create Date: 2026-01-28 23:32:58.802165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a61177eee13'
down_revision: Union[str, Sequence[str], None] = '364c0924848c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('one_time_tokens', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('refresh_tokens', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'version')
    op.drop_column('refresh_tokens', 'version')
    op.drop_column('one_time_tokens', 'version')
    # ### end Alembic commands ###
